### ISSUE TITLE
gcc6 failures with -Werror #pragma

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/libfastjson#112]
Getting a compiler error when building 0.99.3 with gcc 6 only:

```
[   82s] arraylist.c:97:32: error: '-Werror' is not an option that controls warnings [-Werror=pragmas]
[   82s]  #pragma GCC diagnostic ignored "-Werror"
[   82s]                                 ^~~~~~~~~
[   82s] arraylist.c:110:32: error: '-Werror' is not an option that controls warnings [-Werror=pragmas]
[   82s]  #pragma GCC diagnostic ignored "-Werror"
[   82s]                                 ^~~~~~~~~
```

introduced in 8c49ee7490a41486db1c134cae4e5bf6e8599138:

```
#pragma GCC diagnostic push
#ifdef __clang__
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#else
#pragma GCC diagnostic ignored "-Werror"
#endif
```
